### ISSUE TITLE
[3.1] Refresh button is invisible

### ISSUE THREAD

**Issue by lleaff** [willnationsdev/godot-plugin-refresher#1]
After a fresh install on Godot 3.1, the button is functional but invisible.

![image](https://user-images.githubusercontent.com/9746807/47605207-ef56cb80-da03-11e8-804b-15429695097a.png)

**Comment by willnationsdev** [comment]
@lleaff I think this has something to do with the way the icon is being imported. When I downloaded the AssetLib version, the icon was missing as you portrayed. When I opened up the actual plugin refresher scene, changed the icon to something else, and then changed it back, everything was fixed. Furthermore, after I deleted the files from my project, I tried re-downloading first from GitHub directly (which worked), and then again from the AssetLib (which worked).

I noticed that some of the .import files properties were different the very first time I installed the plugin, so my suggestion would just be to try re-importing the icon. I can't reproduce the error anymore.

Let me know if you continue to have any more occurrences of this issue.

**Comment by willnationsdev** [comment]
Have you continued to have problems with this?

**Comment by Xrayez** [comment]
Still relevant in Godot 3.2-dev.

> I think this has something to do with the way the icon is being imported.

Yeah, I think this has something to do with the engine itself, plugins might be registered before anything else and SVG importer fails to import icon in timely manner to update icon path.
